name = "Aoc"
uuid = "c7d7d812-6844-42c1-b1b5-77b3ab8b6314"
authors = ["Penelope Yong <penelopeysm@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
